# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: nullHack/{blog}
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Just a blog to talk about things I like. If you want to read good tutorials,
  thoughts, tips and tricks about computers, free software or photography. this is your place \0.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nullhack.github.io" # the base hostname & protocol for your site
twitter_username: eric_lopes
github_username:  nullhack
flickr_username:  eric-lopes

# Build settings
markdown: kramdown
